require("felipearcaro.plugins-setup")
require("felipearcaro.core.options")
require("felipearcaro.core.keymaps")
require("felipearcaro.core.colorschema")
require("felipearcaro.plugins.telescope")
require("felipearcaro.plugins.lsp.mason")
require("felipearcaro.plugins.nvim-tree")
require("felipearcaro.plugins.lsp.null-ls")
